# Generated by Django 5.1 on 2024-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flan",
            name="rate",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
