# Generated by Django 5.1 on 2024-11-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_flan_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flan",
            name="rate",
            field=models.IntegerField(
                default=None, null=True, verbose_name="Valoración"
            ),
        ),
    ]
